server:
    port: 8088
    servlet:
       context-path: /robot
spring:
    devtools: 
        restart: 
            enabled: true
    servlet:
       multipart:
          max-request-size: 2MB
          max-file-size: 2MB            
    mvc:
       static-path-pattern: /static/**
    datasource:
        name: masterDataSource
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driverClassName: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/robot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
          username: root
          password: 123456
          #配置初始化大小/最小/最大
          initialSize: 1
          minIdle: 1
          maxActive: 20
          #获取连接等待超时时间
          maxWait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          timeBetweenEvictionRunsMillis: 60000
          #一个连接在池中最小生存的时间
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          maxPoolPreparedStatementPerConnectionSize: 20
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
        
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.hs.mapper
    config-location: classpath:mybatis-config.xml
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
swagger:
   enable: true


interface:
   imgServer: http://172.23.35.203:8080/image/
   serverName: /vaswebservice/?singlewsdl
